cc_library(
    name = "create_test_channel",
    srcs = ["create_test_channel.cc"],
    hdrs = [
      "create_test_channel.h",
      "test_credentials_provider.h"
    ],
)


cc_library(
    name = "test_credentials_provider",
    srcs = ["test_credentials_provider.cc"],
    hdrs = [
      "ssl_test_data.h",
      "test_credentials_provider.h"
    ],
)

cc_library(
    name = "ssl_test_data",
    srcs = [
      "client_certs.c",
      "server1_cert.c",
      "server1_key.c",
      "test_root_cert.c",
    ],
    hdrs = [
      "ssl_test_data.h",
    ],
)
